---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci

inputs:
- name: git-kubo-ci
- name: source-json
- name: kubo-lock

run:
  path: /bin/sh
  args:
    - -c
    - |
      git-kubo-ci/scripts/json2yaml.py source-json/source.json >> kubo-lock/metadata