platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable

run:
  path: git-kubo-ci/scripts/update-cloud-config-with-vm-ext-v2.sh

inputs:
- name: source-json
- name: git-kubo-ci
- name: kubo-lock
- name: kubo-deployment
